### ISSUE TITLE
imageboards.json 2.0 has launched!

### ISSUE THREAD

**Issue by bleeny2** [ccd0/imageboards.json#25]
Advantages over the deprecated imageboards.json on Github:
-On GitGud, which doesn't censor unlike Github
-Updated often, only working imageboards are listed
-No dead imageboards that stay on the list for weeks or months
-No favoritism, no imageboards get omitted just because an owner wants it off the list

So come check it out!
**[link removed]**

**Comment by ccd0** [comment]
I'll keep an eye on it for any changes worth incorporating here. Regarding those updates, Britfa.gs, Dramachan, Heyuri, iChan, Math PBBS, Monstrochan, and Wiichan are all working fine. This is why I don't immediately remove entries from the list when the site is down for a day.

**Comment by bleeny2** [comment]
I see you've incorporated a lot of my changes.
Dramachan may be online but the boards have been locked for ages, it's effectively a dead site.
iChan requires approval of posts before they are published which doesn't make it an imageboard.
Wiichan is also online but posting is impossible and has been for ages (gives a DB error).
PS: Slothchan is now also offline.

**Comment by ccd0** [comment]
>Dramachan may be online but the boards have been locked for ages, it's effectively a dead site.

I see plenty of new posts, but on further examination it looks the site is limited to a group of people with accounts rather than open to the general public, so I'll remove it on that basis.

>iChan requires approval of posts before they are published which doesn't make it an imageboard.

Going to have to disagree here. An imageboard is defined by the functionality of posting and discussing images, not the way it is moderated.

>Wiichan is also online but posting is impossible and has been for ages (gives a DB error).
>PS: Slothchan is now also offline.

Thanks, will remove these.

**Comment by bleeny2** [comment]
Secret Area of VIP Quality and Ripper's Anime Page - Music Request Board are textboards.
vgchan, Freech2, Madochan, Spacechan and Spacestro are kill.
See also https://www.diffchecker.com/m6mMiAyg

**Comment by ccd0** [comment]
>Secret Area of VIP Quality and Ripper's Anime Page - Music Request Board are textboards.

Both of those sites have image posting mechanisms although Secret Area of VIP Quality is certainly an edge case since the images aren't very integrated with the text board.

>vgchan, Freech2, Madochan, Spacechan and Spacestro are kill.

I'm aware; they will be removed after waiting a bit for confirmation.

>See also https://www.diffchecker.com/m6mMiAyg

Some of these changes are very bizarre, e.g. changing the URLs of various boards to point to their /int/ boards. And I don't list sites with less than 12 posts per year excluding linkspam. I'll incorporate the changes I think are appropriate.

**Comment by bleeny2** [comment]
mle.party is no longer an imageboard.
