### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by hawkoon** [ccd0/imageboards.json#9]
Dragonchan, Imageboard.fun and Mewch.ru are dead, http://shittyboard.ddns.net and https://leftypol.org/ and http://2axwxq4kqs4kv6qtqomlthsk5sg5tgc2uchalep2uubwre6tryttvyqd.onion/ and https://board.ptown2.com/ and https://archive.lukasengelhardt.net/ and https://aletheia.ee/board/ and http://nfcrew.net/img/imgboard.htm and https://alphachan.net haven't been added yet.
Plus, perhaps it's a good idea to list https://archive.md/wZKhc in your readme? It contains more imageboards than the one on Neinchan did.

**Comment by hawkoon** [comment]
@ccd0 You've added 'https' to the new nanochan URL which should be http.

**Comment by ccd0** [comment]
Added most of those sites and added a blurb in the readme about what is/isn't included.

I generally don't delete sites right away when they go down since it's common for sites to go down intermittently. Unless you know they're down permanently, I'll wait a month or so to confirm and then remove them.

There are a lot of threads where people discuss and list imageboards, so I don't think it's a good idea to add every one to the readme, but I'll look through it when I get the time to see if there are any boards I haven't listed.

Regarding nanochan, they're encouraging people to connect via TLS and their self-signed cert:
http://nanochanpwz3xnue76gteysv6wjm5sim3bbcm2lc65x625at774k77qd.onion/meta/1455.html

**Comment by hawkoon** [comment]
> Added most of those sites and added a blurb in the readme about what is/isn't included.
> 
> I generally don't delete sites right away when they go down since it's common for sites to go down intermittently. Unless you know they're down permanently, I'll wait a month or so to confirm and then remove them.
> 
> There are a lot of threads where people discuss and list imageboards, so I don't think it's a good idea to add every one to the readme, but I'll look through it when I get the time to see if there are any boards I haven't listed.
> 
> Regarding nanochan, they're encouraging people to connect via TLS and their self-signed cert:
> http://nanochanpwz3xnue76gteysv6wjm5sim3bbcm2lc65x625at774k77qd.onion/meta/1455.html

>thread posted a year ago
Self-signed certs are a huge security risk and offer no validation or protection whatsoever. It is unethical to force users to connect to nanochan this way.
As for Imageboard.fun and Dragonchan.net: I owned and closed them. Mega Milk announced on Mewch.xyz that he wasn't going to run an imageboard (Mewch.ru) anymore.

**Comment by ccd0** [comment]
Thanks, updated.
